#!/bin/bash

doit() {
  	NAME=$1
  	# ID=$1
  	# echo ID=$ID
  	# wget http://resource.openra.net/map/id/$ID -O "$ID.dat"
  	# #cat "$ID.dat" | grep "\"title\""
  	# NAME=$(cat "$ID.dat" | grep "\"title\"")
  	# NAME=$(echo ${NAME} | cut -d ' ' -f 2 | cut -d '"' -f 2)
  	# echo NAME=$NAME
  	# wget "https://resource.openra.net/maps/$1/oramap" -O "$NAME.oramap"
  	unzip "$NAME.oramap" -d "$NAME" map.*
	while IFS= read -r line
	do
	  FIRST=$(echo ${line} | cut -d ' ' -f 1)
	  if 	[[ "$FIRST" == "Title:" ]] ; then
	  	#echo $line
	  	line="Title: WW3 v3.0.7 $NAME"
	  fi
	  if 	[[ "$FIRST" == "Author:" ]] ; then
	  	#echo $line
	  	line="Author: H + Waggy + Me"
	  fi

	  if 	[[ "$FIRST" == "Rules:" ]] || \
	  		[[ "$FIRST" == "Sequences:" ]] || \
	  		[[ "$FIRST" == "Weapons:" ]] || \
	  		[[ "$FIRST" == "Voices:" ]] ||
	  		[[ "$FIRST" == "Notifications:" ]] ; then
		  #echo "BREAK"
		  break
	  fi
	  echo "$line" >> "$NAME/map.yaml.new"
	done < "$NAME/map.yaml"
echo "Rules: WW3_Defaults.yaml, WW3_Aircraft.yaml, WW3_Buildings.yaml, WW3_Infantry.yaml, WW3_Misc.yaml, WW3_Ships.yaml, WW3_Vehicles.yaml, WW3_Briefing.yaml, plains.yaml, ai.yaml" >> "$NAME/map.yaml.new"
echo "" >> "$NAME/map.yaml.new"
echo "Sequences: sequences.yaml" >> "$NAME/map.yaml.new"
echo "" >> "$NAME/map.yaml.new"
echo "Weapons: WW3_Weapons.yaml" >> "$NAME/map.yaml.new"
echo "" >> "$NAME/map.yaml.new"
echo "Voices: WW3_Voices.yaml" >> "$NAME/map.yaml.new"
echo "" >> "$NAME/map.yaml.new"
echo "Notifications: notifications.yaml" >> "$NAME/map.yaml.new"
rm "$NAME/map.yaml"
mv "$NAME/map.yaml.new" "$NAME/map.yaml"
cp BASE/* "$NAME" -R
cd "$NAME"
zip "../new/$NAME.oramap" * -r -u
cd ..
rm -rf "$NAME"
}

doit "1000x50"
exit
doit "base-ww3-fast"
doit "1000x1000"
doit "100x300"
doit "400x400"
doit "5x5"
doit "AG1"
doit "AG2"
doit "A.Gardens"
doit "AG"
doit "AG-V"
doit "Amsterdamned"
doit "Anal"
doit "A"
doit "Around"
doit "Backdoor"
doit "Balls1"
doit "Balls2"
doit "Balls2s"
doit "Balls3"
doit "Balls"
doit "base-64x128-ww3"
doit "base"
doit "base-ww3-fast"
doit "BattleStart2"
doit "BattleStart3b"
doit "BattleStart3"
doit "BattleStart"
doit "Bombomblock"
doit "Boxed-ww3"
doit "box-fast"
doit "box-normal"
doit "BOX"
doit "box-ww3-14-2"
doit "box-ww3-14-3"
doit "box-ww3-14-6"
doit "box-ww3-14-new"
doit "box-ww3-fast"
doit "Cavehunter"
doit "Caver"
doit "Caves"
doit "Central"
doit "CERN"
doit "Clash-crash-fixed"
doit "Clash"
doit "DB"
doit "Defence"
doit "Defense"
doit "DizzyBoom2"
doit "DizzyBoom3"
doit "DizzyBoom"
doit "Dizzy"
doit "Ensio_Kaivo2"
doit "Ensio_Kaivo4"
doit "Epstein"
doit "Europe"
doit "EUROPE"
doit "Fallen"
doit "Fastest2"
doit "Fastest3"
doit "Fastest4"
doit "Fastest5"
doit "Fastest6"
doit "Fastest7"
doit "Fastest"
doit "Final"
doit "Floorplan"
doit "Flower"
doit "fm"
doit "Forward2"
doit "Forward3"
doit "Forward"
doit "Gates"
doit "GG"
doit "God's"
doit "Imbus"
doit "Instantatack"
doit "Instantattack"
doit "Interior"
doit "Islands2"
doit "Islands3"
doit "Islands"
doit "killbox"
doit "Knight"
doit "Knight-ww3-v1.0"
doit "Left-Right"
doit "Lion"
doit "Lol"
doit "Long"
doit "Maze-Maniac"
doit "MAZETEST_CURRENT_EDITED"
doit "MDC"
doit "Meet"
doit "Melons"
doit "No"
doit "OCTAGON"
doit "O.Gardens"
doit "OG"
doit "Ore"
doit "Outlaw"
doit "rambo2"
doit "rambo"
doit "Rooms4Rentv2-ww3"
doit "Rooms4Rent-ww3"
doit "Roulette"
doit "Round19h"
doit "Round19"
doit "Round19v"
doit "Shuriken12P"
doit "Shuriken"
doit "Skully-ww3-V0.0"
doit "Slalom"
doit "SMALL"
doit "Smile"
doit "S"
doit "Spiro"
doit "Stargate"
doit "Streetfigther"
doit "Swastika"
doit "Sweet"
doit "Tactic"
doit "TANKX_MAZE2"
doit "TANKX_MAZE3"
doit "TANKX_MAZE"
doit "Taurus"
doit "testing"
doit "The"
doit "ThePooperXL"
doit "Throne"
doit "Toxic"
doit "UC"
doit "UF"
doit "UP"
doit "Worldmap"
doit "world"
doit "WORLD"
doit "WW3_Dry_Europe"
doit "WW3"
doit "Yukon"